version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .env.docker
    volumes:
      - ./log/docker:/app/log
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    expose:
      - 5432
